/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 6.1 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import pt.up.fe.comp.jmm.JmmNode;

import java.lang.RuntimeException;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;


public
class SimpleNode implements Node, JmmNode {

  protected Node parent;
  protected Node[] children;
  protected int id;
  protected Object value;
  protected Jmm parser;

    // added
    public int val;
    public Operator op = null;

  public SimpleNode(int i) {
    id = i;
  }

  public SimpleNode(Jmm p, int i) {
    this(i);
    parser = p;
  }

  /**
   * @return the kind of this node (e.g. MethodDeclaration, ClassDeclaration, etc.)
   */
  public String getKind() {
    return toString();
  }

  // TODO implement this
  /**
   * @return the names of the attributes supported by this Node kind
   */
  public List<String> getAttributes() {
    throw new RuntimeException("Not implemented yet");
  }

  // TODO implement this
  /**
   * Sets the value of an attribute.
   *
   * @param attribute
   * @param value
   */
  public void put(String attribute, String value) {
    throw new RuntimeException("Not implemented yet");
  }

  // TODO implement this
  /**
   *
   * @param attribute
   * @returns the value of an attribute. To see all the attributes iterate the list provided by
   *          {@link JmmNode#getAttributes()}
   */
  public String get(String attribute) {
    throw new RuntimeException("Not implemented yet");
  }

  /**
   *
   * @return the children of the node or an empty list if there are no children
   *
   */
  public List<JmmNode> getChildren() {
    return (children == null) ? new ArrayList<>() : Arrays.asList((JmmNode[])children);
  }

  /**
   *
   * @return the number of children of the node
   */
  public int getNumChildren() {
    return jjtGetNumChildren();
  }

  /**
   * Inserts a node at the given position
   *
   * @param child
   * @param index
   */
  public void add(JmmNode child, int index) {
    if(!(child instanceof Node)) {
  	throw new RuntimeException("Node not supported: " + child.getClass());  
    }
	  
	jjtAddChild((Node) child, index);
  }


  public void jjtOpen() {
  }

  public void jjtClose() {
  }

  public void jjtSetParent(Node n) { parent = n; }
  public Node jjtGetParent() { return parent; }

  public void jjtAddChild(Node n, int i) {
    if (children == null) {
      children = new Node[i + 1];
    } else if (i >= children.length) {
      Node c[] = new Node[i + 1];
      System.arraycopy(children, 0, c, 0, children.length);
      children = c;
    }
    children[i] = n;
  }

  public Node jjtGetChild(int i) {
    return children[i];
  }

  public int jjtGetNumChildren() {
    return (children == null) ? 0 : children.length;
  }

  public void jjtSetValue(Object value) { this.value = value; }
  public Object jjtGetValue() { return value; }

  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(String), otherwise overriding toString() is probably all
     you need to do. */

  public String toString() {
    return JmmTreeConstants.jjtNodeName[id];
  }
  public String toString(String prefix) { return prefix + toString(); }

  /* Override this method if you want to customize how the node dumps
     out its children. */

  public void dump(String prefix) {
    System.out.println(toString(prefix));
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
          n.dump(prefix + " ");
        }
      }
    }
  }

  public int getId() {
    return id;
  }
}

/* JavaCC - OriginalChecksum=d33fdb2b8063d5de3474649324d5d160 (do not edit this line) */
